create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  email text not null,
  organization text not null,
  investment_level text not null,
  ai_experience text not null,
  interests text[] not null default '{}'::text[],
  purpose text not null,
  message text,
  referral_source text,
  privacy_agreed boolean not null,
  status text not null default '접수',
  created_at timestamptz not null default now()
);

create unique index if not exists applications_email_unique_idx
  on public.applications (lower(email));
